################################################################################
#                             DO NOT EDIT THIS FILE                            #
################################################################################
from grid import Grid
from players import Player
    
class Battleship:
    """Basic implementation of a battleship game."""

    def __init__(self,
        player_one:Player, player_two:Player,
        grid_one:Grid, grid_two:Grid,
        debug=False):
        """Initializes the battleship game.
        Args:
            player_one (Player): the first player
            player_two (Player): the second player
            grid_one (Grid): the first grid
            grid_two (Grid): the second grid
        """
        self.player_one = player_one
        self.player_two = player_two
        self.grid_one = grid_one
        self.grid_two = grid_two
        self.debug = debug
    
    def setup(self):
        """Requests each player place their ships."""
        if self.debug: print('Player one placing ships...')
        self.player_one.place_ships(self.grid_one)

        if self.debug: print('Player two placing ships...')
        self.player_two.place_ships(self.grid_two)

    
    def play(self) -> int:
        """Plays the game.
        Returns:
            int: 1 if player one wins, 2 if player two wins.
        """
        move = 0

        while True:
            move += 1
            if self.debug:
                print(f'---------- Round {move} ----------')
                print(self)

            # Player One
            pos = self.player_one.get_move()
            if self.debug: print('Player one targets', pos)
            print(pos)

            result = self.grid_two.target(pos)
            if self.debug: print(result)

            self.player_one.log_result(result)
            if self.grid_two.all_sunk(): return 1, move

            # Player Two
            pos = self.player_two.get_move()
            if self.debug: print('Player two targets', pos)
            print(pos)

            result = self.grid_one.target(pos)
            if self.debug: print(result)

            self.player_two.log_result(result)
            if self.grid_one.all_sunk(): return 2, move
    
    def __str__(self):
        r  = '        Player One             Player Two\n'
        r += '    1 2 3 4 5 6 7 8 9 10   1 2 3 4 5 6 7 8 9 10\n'
        r += '  ╔═════════════════════╗╔═════════════════════╗\n'

        for x in range(10):
            r += f'{chr(x + 65)} ║ '

            for y in range(10):
                pos = Grid.xy_to_pos(x, y)
                cell = self.grid_one.get(pos)
                r += f'{cell} '
            r += '║║ '

            for y in range(10):
                pos = Grid.xy_to_pos(x, y)
                cell = self.grid_two.get(pos)
                r += f'{cell} '
    
            r += '║\n'

        r += '  ╚═════════════════════╝╚═════════════════════╝'
        return r