################################################################################
#                             DO NOT EDIT THIS FILE                            #
################################################################################
from helpers import MoveResult, Orientation, Cell
from ships import Ship
from typing import Tuple

class Grid:
    """A base class for implementations of the Battleship ocean/target grid.
    """

    @staticmethod
    def pos_to_xy(position:str) -> Tuple[int, int]:
        """Accepts a battleship position (A1-J10) and converts it to XY coords.
        Args:
            position (str): the battleship position
        Returns:
            Tuple[int, int]: the XY coordinates
        """
        row, col = position[0], position[1:]
        return ord(row) - 65, int(col) - 1

    @staticmethod
    def xy_to_pos(x:int, y:int) -> str:
        """Accepts XY coordinates and converts it to a battleship position.
        Args:
            x (int): the X coordinate
            y (int): the Y coordinate
        Returns:
            str: the battleship position
        """
        return chr(x + 65) + str(y + 1)
    
    def get(self, position:str) -> Cell:
        """Gets the cell at a specific position.
        Contains info on whether the cell has been targeted and whether there is
        a ship in the cell.
        Args:
            position (str): the position
        Returns:
            Cell: the cell at this position
        """
        raise NotImplementedError()

    def is_valid(self, position:str, orientation:Orientation, ship:Ship) -> bool:
        """Checks if a ship placement is valid.
        Args:
            position (str): the position for the start of the ship
            orientation (Orientation): the orientation of the ship
            ship (Ship): the ship for which to test placement
        Returns:
            bool: True if the placement is valid, False otherwise
        """
        raise NotImplementedError()

    def place(self, position:str, orientation:Orientation, ship:Ship) -> bool:
        """Places a ship on the board.
        Args:
            position (str): the position for the start of the ship
            orientation (Orientation): the orientation of the ship
            ship (Ship): the ship to place
        Returns:
            bool: True if the ship was placed, False otherwise
        """
        raise NotImplementedError()

    def target(self, position:str) -> MoveResult:
        """Calculate the effects of targeting of a specific cell.
        Args:
            position (str): the position targeted
        Returns:
            MoveResult: the result of the targeting
        """
        raise NotImplementedError()
    
    def all_sunk(self) -> bool:
        """Checks if all ships have been sunk.
        Returns:
            bool: True if all ships have been sunk, False otherwise
        """
        raise NotImplementedError()

    def __str__(self):
        r  = '    1 2 3 4 5 6 7 8 9 10\n'
        r += '  ╔═════════════════════╗\n'

        for x in range(10):
            r += f'{chr(x + 65)} ║ '

            for y in range(10):
                pos = Grid.xy_to_pos(x, y)
                cell = self.get(pos)
                r += f'{cell} '
            r += '║\n'
        r += '  ╚═════════════════════╝'
        return r