################################################################################
#                             DO NOT EDIT THIS FILE                            #
################################################################################
from ships import Ship
from enum import Enum, unique

class Cell:
    """The contents of a cell in the Grid.

    Properties:
        targeted (bool): True if the position has been targetted
        ship (Ship): The ship at the position, if any.
    """
    def __init__(self, targeted:bool, ship:Ship):
        self.targeted = targeted
        self.ship = ship
    
    def __str__(self):
        if self.ship:
            return chr(
                self.ship.sid +
                (10101 if self.targeted else 9311))

        else:
            return '●' if self.targeted else '○'

class MoveResult:
    """The result of a move.

    Properties:
        position (str): The position which was targeted
        ship (Ship): The ship at the position, or None
        is_sunk (bool): True if the ship hit was sunk
    """
    def __init__(self, position:str, ship:Ship, is_sunk:bool):
        self.position = position
        self.ship = ship
        self.is_sunk = is_sunk

    def __str__(self):
        if self.is_sunk:
            return f'sunk {self.ship.name} @ {self.position}'
        elif self.ship:
            return f'hit {self.ship.name} @ {self.position}'
        else:
            return f'miss @ {self.position}'

@unique
class Orientation(Enum):
    """Orientations for ships."""
    HORIZONTAL = 'h'
    VERTICAL = 'v'

    @staticmethod
    def all():
        return list(Orientation)