################################################################################
#                             DO NOT EDIT THIS FILE                            #
################################################################################
from grid import Grid
from ships import Ships
from helpers import MoveResult, Orientation
import random

class Player:
    """An battleship player."""

    def log_result(self, result:MoveResult) -> None:
        """Logs the result of a move.

        Args:
            result (MoveResult): the result of the move.
        """
        pass

    def place_ships(self, grid:Grid) -> None:
        """Places the ships for a game.

        Args:
            grid (Grid): the grid on which to place the ships
        """
        raise NotImplementedError()

    def get_move(self) -> str:
        """Gets a move.

        Returns:
            str: the move
        """
        raise NotImplementedError()


class SimplePlayer(Player):
    def __init__(self):
        self.move = 0

    def place_ships(self, grid):
        grid.place('A1', Orientation.HORIZONTAL, Ships.CARRIER)
        grid.place('A10', Orientation.VERTICAL, Ships.BATTLESHIP)
        grid.place('J8', Orientation.HORIZONTAL, Ships.CRUISER)
        grid.place('H1', Orientation.VERTICAL, Ships.SUBMARINE)
        grid.place('F5', Orientation.HORIZONTAL, Ships.DESTROYER)
    
    def get_move(self):
        x = self.move // 10
        y = self.move % 10
        self.move += 1
        return Grid.xy_to_pos(x, y)

class RandomPlayer(Player):
    def __init__(self):
        self.moves = list(range(100))

    def place_ships(self, grid):
        for ship in Ships.ALL:
            while True:
                orientation = random.choice(Orientation.all())
                x = random.randint(0, 9)
                y = random.randint(0, 9)
                pos = Grid.xy_to_pos(x, y)
                
                if grid.is_valid(pos, orientation, ship):
                    grid.place(pos, orientation, ship)
                    break
    
    def get_move(self):
        move = random.choice(self.moves)
        self.moves.remove(move)

        x = move // 10
        y = move % 10
        return Grid.xy_to_pos(x, y)