################################################################################
#                             DO NOT EDIT THIS FILE                            #
################################################################################
class Ship:
    """Basic information about a ship.

    Properties:
        name (str): The ship name
        sid (int): A unique ID for the ship
        size (int): The size of the ship
    """
    def __init__(self, name, sid, size):
        self.name = name
        self.sid = sid
        self.size = size


class Ships:
    """A collection of ships for the game."""

    # The ships
    CARRIER = Ship('Carrier', 2, 5)
    BATTLESHIP = Ship('Battleship', 3, 4)
    CRUISER = Ship('Cruiser', 4, 3)
    SUBMARINE = Ship('Submarine', 5, 3)
    DESTROYER = Ship('Destroyer', 6, 2)

    # All The ships in a list, for easy iteration.
    ALL = [ CARRIER, BATTLESHIP, CRUISER, SUBMARINE, DESTROYER ]


    _ID2SHIP = { s.sid: s for s in ALL }   

    @staticmethod
    def from_id(ship_id):
        """Gets a ship from it's ID.

        Args:
            ship_id (int): the ship's ID

        Returns:
            Ship: the ship or None
        """
        return Ships._ID2SHIP.get(ship_id, None)
        